export const subjects = {
  Literature: 'literature',
  Romance: 'romance',
  Comedy: 'comedy',
  Horror: 'horror',
  Thriller: 'thriller',
  Detective: 'detective',
}

export const GENRES = {
  Art: 'art',
  Biography: 'biography',
  Classics: 'classics',
  Comics: 'comics',
  Fantasy: 'fantasy',
  Fiction: 'fiction',
  'Historical Fiction': 'historical-fiction',
  History: 'history',
  Horror: 'horror',
  Memoir: 'memoir',
  Mystery: 'mystery',
  Nonfiction: 'nonfiction',
  Poetry: 'poetry',
  Psychology: 'psychology',
  Romance: 'romance',
  Science: 'science',
  'Science Fiction': 'sci-fi',
  'Self Help': 'self-help',
  Thriller: 'thriller',
  Travel: 'travel',
  'Young Adult': 'young-adults',
}
